### ISSUE TITLE
Load a flag from local file BY CODE

### ISSUE THREAD

**Issue by duainsulch** [krikienoid/flagwavertest#1]
hello, i am trying to load a flag from local file but passing the file by code, anyone can help on how to do that? thks

**Comment by krikienoid** [comment]
By local file, do you mean from your computer's file system, or from a local server? Are you writing code in JavaScript or some other language?

Also please post issues to https://github.com/krikienoid/flagwaver. The flagwavertest repo is just for testing

**Comment by duainsulch** [comment]
thks, i open the issue on the link that you provide
